// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbucfvowctlpmlgjudvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNidWNmdm93Y3RscG1sZ2p1ZHZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3ODMyMTEsImV4cCI6MjA2MjM1OTIxMX0.zlVVnLuFXsn1g9oloJs8-JS2U_BV3bA2Q8P4Xrc8Ric";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);