// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbfvbgagewtqqorurdix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iZnZiZ2FnZXd0cXFvcnVyZGl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDQwOTUsImV4cCI6MjA2NDc4MDA5NX0.Dv3ZLv0s3Radp44IXylFjhYPKyJhblDdm6DS7jfHZHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);